name: CI

# When to run the workflow
on:
  push:       # Run on any push to main branch
    branches: [ main ]
  pull_request:   # Run on pull requests targeting main
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest   # Use a Linux VM
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v
